name: Deploy to Firebase Hosting on merge

'on':
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: flutter_application_1/functions
    steps:
      - uses: actions/checkout@v3
      

      - name: Ensure package-lock.json exists
        run: |
          if [ ! -f package-lock.json ]; 
          then
              npm install
          fi

      - run: npm ci && npm run shell


      # Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GAYMEATUP }}'
          channelId: live
          projectId: gaymeatup
